export default[
    {
        paletteName: "Material UI Colors",
        id: "material-ui-colors",
        emoji: "x",
        colors: [
            { name: "red", color:"#f8d336" },
            { name: "pink", color:"#C4f82E" },
            { name: "purple", color:"#f423f6" },
            { name: "deeppurple", color:"#ff4336" },
            { name: "indigo", color:"#f443d6" },
            { name: "blue", color:"#f64f36" },
            { name: "lightgreen", color:"#c3f4f6" },
            { name: "cyan", color:"#f4df36" },
            { name: "lightBlue", color:"#fc4f36" },
            { name: "amber", color:"#C4782E" },
            { name: "orange", color:"#101D07" },
            { name: "deeporange", color:"#C4482E" },
            { name: "lightbllue", color:"#fd4f36" },
            { name: "brown", color:"#f4fd56" },
            { name: "grey", color:"#f44d56" },
            { name: "lime", color:"#fff556" },
            { name: "teal", color:"#443f36" },
            { name: "green", color:"#4ff336" },
            { name: "cyyan", color:"#f44f36" },
            
        ]
    },
    {
        paletteName: "Material UI Colorss",
        id: "material-ui-colorss",
        emoji: "x",
        colors: [
            { name: "red", color:"#f8d336" },
            { name: "pink", color:"#C4f82E" },
            { name: "purple", color:"#f423f6" },
            { name: "deeppurple", color:"#ff4336" },
            { name: "indigo", color:"#f443d6" },
            { name: "blue", color:"#fd4f36" },
            { name: "lightgreen", color:"#c3f4f6" },
            { name: "cyan", color:"#f4df36" },
            { name: "lightBlue", color:"#fc4f36" },
            { name: "amber", color:"#C4482E" },
            { name: "orange", color:"#101D07" },
            { name: "deeporange", color:"#C4482E" },
            { name: "lightbllue", color:"#fd4f36" },
            { name: "brown", color:"#f4fd56" },
            { name: "grey", color:"#f44d56" },
            { name: "bluegrey", color:"#f4f776" },
            { name: "lime", color:"#fff556" },
            { name: "teal", color:"#443f36" },
            { name: "green", color:"#4ff336" },
            { name: "cyyan", color:"#f4df36" },
            
        ]
    },
    {
        paletteName: "Material UI Coloras",
        id: "material-ui-coloras",
        emoji: "x",
        colors: [
            { name: "red", color:"#f8d336" },
            { name: "pink", color:"#C4f82E" },
            { name: "purple", color:"#f423f6" },
            { name: "deeppurple", color:"#ff4336" },
            { name: "indigo", color:"#f443d6" },
            { name: "blue", color:"#fd4f36" },
            { name: "lightgreen", color:"#c3f4f6" },
            { name: "cyan", color:"#f4df36" },
            { name: "lightBlue", color:"#fc4f36" },
            { name: "amber", color:"#C4482E" },
            { name: "orange", color:"#101D07" },
            { name: "deeporange", color:"#C4482E" },
            { name: "lightbllue", color:"#fd4f36" },
            { name: "brown", color:"#f4fd56" },
            { name: "grey", color:"#f44d56" },
            { name: "bluegrey", color:"#f4f776" },
            { name: "lime", color:"#fff556" },
            { name: "teal", color:"#443f36" },
            { name: "green", color:"#4ff336" },
            { name: "cyyan", color:"#f4df36" },
            
        ]
    },
    {
        paletteName: "Material UI Coalors",
        id: "material-ui-coalors",
        emoji: "x",
        colors: [
            { name: "red", color:"#f8d336" },
            { name: "pink", color:"#C4f82E" },
            { name: "purple", color:"#f423f6" },
            { name: "deeppurple", color:"#ff4336" },
            { name: "indigo", color:"#f443d6" },
            { name: "blue", color:"#fd4f36" },
            { name: "lightgreen", color:"#c3f4f6" },
            { name: "cyan", color:"#f4df36" },
            { name: "lightBlue", color:"#fc4f36" },
            { name: "amber", color:"#C4482E" },
            { name: "orange", color:"#101D07" },
            { name: "deeporange", color:"#C4482E" },
            { name: "lightbllue", color:"#fd4f36" },
            { name: "brown", color:"#f4fd56" },
            { name: "grey", color:"#f44d56" },
            { name: "bluegrey", color:"#f4f776" },
            { name: "lime", color:"#fff556" },
            { name: "teal", color:"#443f36" },
            { name: "green", color:"#4ff336" },
            { name: "cyyan", color:"#f4df36" },
            
        ]
    },
    {
        paletteName: "Material UI aColors",
        id: "material-ui-acolors",
        emoji: "x",
        colors: [
            { name: "red", color:"#f8d336" },
            { name: "pink", color:"#C4f82E" },
            { name: "purple", color:"#f423f6" },
            { name: "deeppurple", color:"#ff4336" },
            { name: "indigo", color:"#f443d6" },
            { name: "blue", color:"#fd4f36" },
            { name: "lightgreen", color:"#c3f4f6" },
            { name: "cyan", color:"#f4df36" },
            { name: "lightBlue", color:"#fc4f36" },
            { name: "amber", color:"#C4482E" },
            { name: "orange", color:"#101D07" },
            { name: "deeporange", color:"#C4482E" },
            { name: "lightbllue", color:"#fd4f36" },
            { name: "brown", color:"#f4fd56" },
            { name: "grey", color:"#f44d56" },
            { name: "bluegrey", color:"#f4f776" },
            { name: "lime", color:"#fff556" },
            { name: "teal", color:"#443f36" },
            { name: "green", color:"#4ff336" },
            { name: "cyyan", color:"#f4df36" },
            
        ]
    },
    {
        paletteName: "Materialaa UI Colors",
        id: "materialaa-ui-colors",
        emoji: "x",
        colors: [
            { name: "red", color:"#f8d336" },
            { name: "pink", color:"#C4f82E" },
            { name: "purple", color:"#f423f6" },
            { name: "deeppurple", color:"#ff4336" },
            { name: "indigo", color:"#f443d6" },
            { name: "blue", color:"#fd4f36" },
            { name: "lightgreen", color:"#c3f4f6" },
            { name: "cyan", color:"#f4df36" },
            { name: "lightBlue", color:"#fc4f36" },
            { name: "amber", color:"#C4482E" },
            { name: "orange", color:"#101D07" },
            { name: "deeporange", color:"#C4482E" },
            { name: "lightbllue", color:"#fd4f36" },
            { name: "brown", color:"#f4fd56" },
            { name: "grey", color:"#f44d56" },
            { name: "bluegrey", color:"#f4f776" },
            { name: "lime", color:"#fff556" },
            { name: "teal", color:"#443f36" },
            { name: "green", color:"#4ff336" },
            { name: "cyyan", color:"#f4df36" },
            
        ]
    },
    {
        paletteName: "Materaial UI Colors",
        id: "materaial-ui-colors",
        emoji: "x",
        colors: [
            { name: "red", color:"#f8d336" },
            { name: "pink", color:"#C4f82E" },
            { name: "purple", color:"#f423f6" },
            { name: "deeppurple", color:"#ff4336" },
            { name: "indigo", color:"#f443d6" },
            { name: "blue", color:"#fd4f36" },
            { name: "lightgreen", color:"#c3f4f6" },
            { name: "cyan", color:"#f4df36" },
            { name: "lightBlue", color:"#fc4f36" },
            { name: "amber", color:"#C4482E" },
            { name: "orange", color:"#101D07" },
            { name: "deeporange", color:"#C4482E" },
            { name: "lightbllue", color:"#fd4f36" },
            { name: "brown", color:"#f4fd56" },
            { name: "grey", color:"#f44d56" },
            { name: "bluegrey", color:"#f4f776" },
            { name: "lime", color:"#fff556" },
            { name: "teal", color:"#443f36" },
            { name: "green", color:"#4ff336" },
            { name: "cyyan", color:"#f4df36" },
            
        ]
    },
    {
        paletteName: "Mataerial UI Colors",
        id: "Mataerial-UI-Colors",
        emoji: "x",
        colors: [
            { name: "red", color:"#f8d336" },
            { name: "pink", color:"#C4f82E" },
            { name: "purple", color:"#f423f6" },
            { name: "deeppurple", color:"#ff4336" },
            { name: "indigo", color:"#f443d6" },
            { name: "blue", color:"#fd4f36" },
            { name: "lightgreen", color:"#c3f4f6" },
            { name: "cyan", color:"#f4df36" },
            { name: "lightBlue", color:"#fc4f36" },
            { name: "amber", color:"#C4482E" },
            { name: "orange", color:"#101D07" },
            { name: "deeporange", color:"#C4482E" },
            { name: "lightbllue", color:"#fd4f36" },
            { name: "brown", color:"#f4fd56" },
            { name: "grey", color:"#f44d56" },
            { name: "bluegrey", color:"#f4f776" },
            { name: "lime", color:"#fff556" },
            { name: "teal", color:"#443f36" },
            { name: "green", color:"#4ff336" },
            { name: "cyyan", color:"#f4df36" },
            
        ]
    },
]